# Generated by Django 6.0.6 on 2026-06-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_id_alter_class_id_alter_position_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Class_name',
        ),
    ]
